name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build discovery-service
      run: mvn -B package --file discovery-service/pom.xml
    - name: Build students-service
      run: mvn -B package --file students-service/pom.xml
    - name: Build subjects-service
      run: mvn -B package --file subjects-service/pom.xml

  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [ 'java' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          no-autobuild: false

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v2
        with:
          directory: students-service
